name: workflow1
on: [workflow_dispatch]
jobs: 
  jobJava: 
   runs-on: ubuntu-latest
   steps: 
    - name: check java version
      run:  java -version
    - name: create java code
      run:  |
          echo 'public class Hello { public static void main(String args[]) { System.out.println("Hello from Github actions"); } }' > Hello.java
          ls -a
          cat Hello.java
    - name: compile java code
      run: |
          javac Hello.java
          ls -a
    - name: run java code
      run: java Hello
       
      
